
import os
from astropy.coordinates import SkyCoord
import astropy.units as u

'''
Run all of the THINGS and LITTLE THINGS HI cubes (at least those used for
Bagetakos+11).

We'll create a catalog of bubbles across the sample and compare to the
Bagetakos catalog.
'''

things_path = "/media/eric/Data_3/VLA/THINGS/"

# Properties from Table 1 in Walter+08 and scale heights from Bagetakos+11
# (Table 3)

# Define the list of galaxies to run on
galaxy_props = {"NGC_628": {"name": "NGC 628",
                            "center_coord": SkyCoord("01h36m41.8",
                                                     "+15d47m0.0",
                                                     frame='icrs'),
                            "inclination": 7 * u.deg,
                            "position_angle": 20 * u.deg,
                            "scale_height": 490 * u.pc,
                            "distance": 7.3 * u.Mpc},  # M74
                "NGC_2366": {"name": "NGC 2366",
                             "center_coord": SkyCoord("07h28m53.4",
                                                      "+69d12m51.0",
                                                      frame='icrs'),
                             "inclination": 64 * u.deg,
                             "position_angle": 40 * u.deg,
                             "scale_height": 510 * u.pc,
                             "distance": 3.4 * u.Mpc},  # DDO 42
                "NGC_2403": {"name": "NGC 2403",
                             "center_coord": SkyCoord("07h36m51.1",
                                                      "+65d36m03.0",
                                                      frame='icrs'),
                             "inclination": 63 * u.deg,
                             "position_angle": 124 * u.deg,
                             "scale_height": 360. * u.pc,
                             "distance": 3.2 * u.Mpc},
                "HO_II": {"name": "Holmberg II",
                          "center_coord": SkyCoord("08h19m05.0",
                                                   "+70d43m12.0",
                                                   frame='icrs'),
                          "inclination": 41 * u.deg,
                          "position_angle": 177.0 * u.deg,
                          "scale_height": 340. * u.pc,
                          "distance": 3.4 * u.Mpc},  # DDO 50
                "DDO53": {"name": "DDO 53",
                          "center_coord": SkyCoord("08h34m07.2",
                                                   "+66d10m54.0",
                                                   frame='icrs'),
                          "inclination": 31 * u.deg,
                          "position_angle": 132 * u.deg,
                          "scale_height": 290. * u.pc,
                          "distance": 3.6 * u.Mpc},
                "NGC_2841": {"name": "NGC 2841",
                             "center_coord": SkyCoord("09h22m02.6",
                                                      "+50d58m35.0",
                                                      frame='icrs'),
                             "inclination": 74 * u.deg,
                             "position_angle": 153 * u.deg,
                             "scale_height": 480 * u.pc,
                             "distance": 14.1 * u.Mpc},
                "HO_I": {"name": "Holmberg I",
                         "center_coord": SkyCoord("09h40m32.3",
                                                  "+71d10m56.0",
                                                  frame='icrs'),
                         "inclination": 12 * u.deg,
                         "position_angle": 50 * u.deg,
                         "scale_height": 640 * u.pc,
                         "distance": 3.8 * u.Mpc},
                "NGC_2976": {"name": "NGC 2976",
                             "center_coord": SkyCoord("09h47m15.3",
                                                      "+67d55m0.0",
                                                      frame='icrs'),
                             "inclination": 65 * u.deg,
                             "position_angle": 335 * u.deg,
                             "scale_height": 120 * u.pc,
                             "distance": 3.6 * u.Mpc},
                "NGC_3031": {"name": "NGC 3031",
                             "center_coord": SkyCoord("09h55m33.1",
                                                      "+69d03m55.0",
                                                      frame='icrs'),
                             "inclination": 59 * u.deg,
                             "position_angle": 330 * u.deg,
                             "scale_height": 140 * u.pc,
                             "distance": 3.6 * u.Mpc},  # M81
                "NGC_3184": {"name": "NGC 3184",
                             "center_coord": SkyCoord("10h18m17.0",
                                                      "+41d25m28.0",
                                                      frame='icrs'),
                             "inclination": 16 * u.deg,
                             "position_angle": 179 * u.deg,
                             "scale_height": 310 * u.pc,
                             "distance": 11.1 * u.Mpc},
                "IC_2574": {"name": "IC 2574",
                            "center_coord": SkyCoord("10h28m27.7",
                                                     "+68d24m59.0",
                                                     frame='icrs'),
                            "inclination": 53 * u.deg,
                            "position_angle": 56 * u.deg,
                            "scale_height": 290 * u.pc,
                            "distance": 4.0 * u.Mpc},  # DDO 81,
                "NGC_3521": {"name": "NGC 3521",
                             "center_coord": SkyCoord("11h05m48.6",
                                                      "-00d02m09.0",
                                                      frame='icrs'),
                             "inclination": 73 * u.deg,
                             "position_angle": 340 * u.deg,
                             "scale_height": 330 * u.pc,
                             "distance": 10.7 * u.Mpc},
                "NGC_3627": {"name": "NGC 3627",
                             "center_coord": SkyCoord("11h20m15.0",
                                                      "+12d59m30.0",
                                                      frame='icrs'),
                             "inclination": 62 * u.deg,
                             "position_angle": 173 * u.deg,
                             "scale_height": 140 * u.pc,
                             "distance": 9.3 * u.Mpc},
                "NGC_4214": {"name": "NGC 4214",
                             "center_coord": SkyCoord("12h15m39.2",
                                                      "+36d19m37.0",
                                                      frame='icrs'),
                             "inclination": 44 * u.deg,
                             "position_angle": 65 * u.deg,
                             "scale_height": 140 * u.pc,
                             "distance": 2.9 * u.Mpc},
                "NGC_4449": {"name": "NGC 4449",
                             "center_coord": SkyCoord("12h28m11.9",
                                                      "+44d05m40.0",
                                                      frame='icrs'),
                             "inclination": 60 * u.deg,
                             "position_angle": 230 * u.deg,
                             "scale_height": 400 * u.pc,
                             "distance": 4.2 * u.Mpc},
                "NGC_4736": {"name": "NGC 4736",
                             "center_coord": SkyCoord("12h50m53.0",
                                                      "+41d07m13.0",
                                                      frame='icrs'),
                             "inclination": 41 * u.deg,
                             "position_angle": 296 * u.deg,
                             "scale_height": 3.6 * u.Mpc,
                             "distance": 4.7 * u.Mpc},  # M94
                "DDO154": {"name": "DDO 154",
                           "center_coord": SkyCoord("12h54m05.9",
                                                    "+27d00m10.0",
                                                    frame='icrs'),
                           "inclination": 66 * u.deg,
                           "position_angle": 230 * u.deg,
                           "scale_height": 540 * u.pc,
                           "distance": 4.3 * u.Mpc},  # NGC_4789A
                "NGC_5194": {"name": "NGC 5194",  # M51a
                             "center_coord": SkyCoord("13h29m52.7",
                                                      "+47d11m43.0",
                                                      frame='icrs'),
                             "inclination": 42 * u.deg,
                             "position_angle": 172 * u.deg,
                             "scale_height": 160 * u.pc,
                             "distance": 8.0 * u.Mpc},
                "NGC_6946": {"name": "NGC 6946",
                             "center_coord": SkyCoord("20h34m52.7",
                                                      "+60d09m14.0",
                                                      frame='icrs'),
                             "inclination": 33 * u.deg,
                             "position_angle": 243 * u.deg,
                             "scale_height": 280.0 * u.pc,
                             "distance": 5.9 * u.Mpc},
                "NGC_7793": {"name": "NGC 7793",
                             "center_coord": SkyCoord("23h57m49.7",
                                                      "-32d35m28.0",
                                                      frame='icrs'),
                             "inclination": 50 * u.deg,
                             "position_angle": 290 * u.deg,
                             "scale_height": 260 * u.pc,
                             "distance": 3.9 * u.Mpc}
                }
